/**
 * Pre-built themes for the portfolio
 * Each theme includes colors, typography, and layout settings
 */

export const PREBUILT_THEMES = [
  {
    name: "modern",
    displayName: "Modern",
    description: "Clean and contemporary with vibrant accents",
    colors: {
      primary: "#3B82F6",
      accent: "#FFD700",
      background: "oklch(1 0 0)",
      foreground: "oklch(0.235 0.015 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.235 0.015 65)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#10B981",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "3rem",
      bodyFontSize: "1rem",
      headingFontWeight: "700",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "elevated",
      spacing: "medium",
    },
  },
  {
    name: "minimal",
    displayName: "Minimal",
    description: "Minimalist design with focus on content",
    colors: {
      primary: "#000000",
      accent: "#FFFFFF",
      background: "oklch(1 0 0)",
      foreground: "oklch(0 0 0)",
      card: "oklch(0.98 0.001 286.375)",
      cardForeground: "oklch(0 0 0)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#059669",
      warning: "#D97706",
      error: "#DC2626",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "2.5rem",
      bodyFontSize: "1rem",
      headingFontWeight: "600",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "list",
      cardStyle: "outlined",
      spacing: "spacious",
    },
  },
  {
    name: "dark",
    displayName: "Dark Mode",
    description: "Dark theme with high contrast",
    colors: {
      primary: "#60A5FA",
      accent: "#FBBF24",
      background: "oklch(0.141 0.005 285.823)",
      foreground: "oklch(0.85 0.005 65)",
      card: "oklch(0.21 0.006 285.885)",
      cardForeground: "oklch(0.85 0.005 65)",
      border: "oklch(1 0 0 / 10%)",
      success: "#34D399",
      warning: "#FBBF24",
      error: "#F87171",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "3rem",
      bodyFontSize: "1rem",
      headingFontWeight: "700",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "filled",
      spacing: "medium",
    },
  },
  {
    name: "colorful",
    displayName: "Colorful",
    description: "Vibrant and playful with multiple accent colors",
    colors: {
      primary: "#8B5CF6",
      accent: "#EC4899",
      background: "oklch(0.98 0.001 286.375)",
      foreground: "oklch(0.235 0.015 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.235 0.015 65)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#06B6D4",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "3.5rem",
      bodyFontSize: "1.125rem",
      headingFontWeight: "800",
      bodyFontWeight: "500",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "elevated",
      spacing: "compact",
    },
  },
  {
    name: "professional",
    displayName: "Professional",
    description: "Corporate and business-focused design",
    colors: {
      primary: "#1E40AF",
      accent: "#0F766E",
      background: "oklch(0.98 0.001 286.375)",
      foreground: "oklch(0.2 0.01 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.2 0.01 65)",
      border: "oklch(0.9 0.005 286.32)",
      success: "#047857",
      warning: "#B45309",
      error: "#991B1B",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "2.75rem",
      bodyFontSize: "1rem",
      headingFontWeight: "700",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "outlined",
      spacing: "medium",
    },
  },
  {
    name: "creative",
    displayName: "Creative",
    description: "Artistic and expressive with unique styling",
    colors: {
      primary: "#DC2626",
      accent: "#F97316",
      background: "oklch(1 0 0)",
      foreground: "oklch(0.235 0.015 65)",
      card: "oklch(0.98 0.001 286.375)",
      cardForeground: "oklch(0.235 0.015 65)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#16A34A",
      warning: "#EA580C",
      error: "#DC2626",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "4rem",
      bodyFontSize: "1.125rem",
      headingFontWeight: "900",
      bodyFontWeight: "500",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "elevated",
      spacing: "spacious",
    },
  },
  {
    name: "startup",
    displayName: "Startup",
    description: "Modern and energetic for tech startups",
    colors: {
      primary: "#7C3AED",
      accent: "#06B6D4",
      background: "oklch(0.98 0.001 286.375)",
      foreground: "oklch(0.235 0.015 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.235 0.015 65)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#10B981",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "3.5rem",
      bodyFontSize: "1rem",
      headingFontWeight: "800",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "elevated",
      spacing: "compact",
    },
  },
  {
    name: "corporate",
    displayName: "Corporate",
    description: "Enterprise-grade professional design",
    colors: {
      primary: "#003366",
      accent: "#0099CC",
      background: "oklch(0.98 0.001 286.375)",
      foreground: "oklch(0.2 0.01 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.2 0.01 65)",
      border: "oklch(0.88 0.005 286.32)",
      success: "#006633",
      warning: "#996600",
      error: "#990000",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "2.5rem",
      bodyFontSize: "1rem",
      headingFontWeight: "600",
      bodyFontWeight: "400",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "outlined",
      spacing: "medium",
    },
  },
  {
    name: "artistic",
    displayName: "Artistic",
    description: "Creative portfolio with artistic flair",
    colors: {
      primary: "#9333EA",
      accent: "#EC4899",
      background: "oklch(0.97 0.002 286.375)",
      foreground: "oklch(0.235 0.015 65)",
      card: "oklch(1 0 0)",
      cardForeground: "oklch(0.235 0.015 65)",
      border: "oklch(0.92 0.004 286.32)",
      success: "#059669",
      warning: "#D97706",
      error: "#DC2626",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "3.75rem",
      bodyFontSize: "1.125rem",
      headingFontWeight: "900",
      bodyFontWeight: "500",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "elevated",
      spacing: "spacious",
    },
  },
  {
    name: "bold",
    displayName: "Bold",
    description: "High contrast and attention-grabbing",
    colors: {
      primary: "#000000",
      accent: "#FF0000",
      background: "oklch(1 0 0)",
      foreground: "oklch(0 0 0)",
      card: "oklch(0.95 0.001 286.375)",
      cardForeground: "oklch(0 0 0)",
      border: "oklch(0 0 0)",
      success: "#00AA00",
      warning: "#FFAA00",
      error: "#FF0000",
    },
    typography: {
      headingFontFamily: "Sora",
      bodyFontFamily: "Sora",
      headingFontSize: "4rem",
      bodyFontSize: "1.125rem",
      headingFontWeight: "900",
      bodyFontWeight: "600",
    },
    layout: {
      sectionLayout: "grid",
      cardStyle: "filled",
      spacing: "compact",
    },
  },
];
